# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/setup-node@v1
    - run: npm i -g serverless
    - run: npm i serverless-domain-manager --save-dev
    - run: ./gradlew deploy-lambda-dev --no-daemon
  
